#!/bin/bash
if [ "$1" == "CreateDump" ]; then
	if [ "$( psql -tAc "SELECT 1 FROM pg_database WHERE datname='LariumDB'" )" = '1' ]; then
		pg_dump -U $USER LariumDB > Sources/Data/dbexport.pgsql
		echo "Dump created in Source/Data/"
	else
		echo "LariumDB does not exist"
	fi
fi
if [ "$1" == "CreateDB" ]; then
	if [ "$( psql -tAc "SELECT 1 FROM pg_database WHERE datname='LariumDB'" )" = '1' ]; then
		while ( [ "$K" != "y" ] && [ "$K" != "n" ]  ) do
			echo "LariumDB already exists, do you want to replace it? y/n"
			read -n 1 K
			echo
		done
		if [ "$K" == "y" ]; then
			dropdb LariumDB
		else
			exit
		fi
	fi
	createdb LariumDB
	psql -U $USER LariumDB < Sources/Data/dbexport.pgsql
	echo "LariumDB now contains data from dbexport.pgsql"
fi

